// Code generated by MockGen. DO NOT EDIT.
// Source: api/client.go
//
// Generated by this command:
//
//	mockgen -source api/client.go -destination api/mock-httpclient/client.go HttpCilent
//

// Package mock_api is a generated GoMock package.
package mock_api

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHttpCilent is a mock of HttpCilent interface.
type MockHttpCilent struct {
	ctrl     *gomock.Controller
	recorder *MockHttpCilentMockRecorder
	isgomock struct{}
}

// MockHttpCilentMockRecorder is the mock recorder for MockHttpCilent.
type MockHttpCilentMockRecorder struct {
	mock *MockHttpCilent
}

// NewMockHttpCilent creates a new mock instance.
func NewMockHttpCilent(ctrl *gomock.Controller) *MockHttpCilent {
	mock := &MockHttpCilent{ctrl: ctrl}
	mock.recorder = &MockHttpCilentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpCilent) EXPECT() *MockHttpCilentMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHttpCilent) Do(arg0 *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", arg0)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHttpCilentMockRecorder) Do(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHttpCilent)(nil).Do), arg0)
}
